contract:
  external:
    book:
      google:
        url: https://www.googleapis.com
        key: AIzaSyARlz5ihS0A2ly9VPiHBmPSIqFhc0PJ0wU
        max: 5
    album:
      itune:
        url: https://itunes.apple.com/search
        max: 5

spring:
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
    openfeign:
      client:
        config:
          default:
            connect-timeout: 10000
            read-timeout: 20000
  graphql:
    graphiql:
      enabled: true

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'

#CIRCUIT BREAKER
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 30
        waitDurationInOpenState: 10s
        failureRateThreshold: 70
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
        slidingWindowType: "COUNT_BASED"
        slowCallRateThreshold: 90
        slowCallDurationThreshold: 40s
        recordExceptions:
          - org.atousa.items.exception.TimeoutContractException